server:
  port: 8130

spring:
  profiles:
    active: dev
  application:
    name: service-oss

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    keyId: LTAI5tHDfNyAsNSK9apo1ytU
    keySecret: KWzKHLtyxUURM7W1bBLV0InuIXz3Li
    bucketName: guli-filehy