server:
  port: 9001
spring:
  application:
    name: sunmore-base
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false